import gradio as gr
from TTS.api import TTS

# -----------------------------------------------------------
# Load pretrained model (directly from the web)
# -----------------------------------------------------------
tts = TTS("tts_models/en/ljspeech/vits--neon", progress_bar=False, gpu=False)

# -----------------------------------------------------------
# Convert text into voice and save to temporary audio file
# -----------------------------------------------------------
def text_to_speech(text):
    if not text.strip():
        return None

    # Generate speech and save to temporary file
    output_path = "output.wav"
    tts.tts_to_file(text=text, file_path=output_path)
    return output_path

# -----------------------------------------------------------
# Gradio Web Interface
# -----------------------------------------------------------
demo = gr.Interface(
    fn=text_to_speech,
    inputs=gr.Textbox(lines=2, placeholder="Type text like 'Hello, I am your AI voice!'"),
    outputs=gr.Audio(type="filepath"),
    title="Voice Cloning & Synthesis System Using VITS + HiFi-GAN",
    description="Enter any English text and listen to realistic human-like speech generated by VITS + HiFi-GAN.",
)

demo.launch()
